exports.CARD_SCREENS = [
  "testsToday",
  "testsTodayHAT",
  "hospitalizedCurrent",
  "icuCurrent",
  "deceasedToDate",
  "casesAvg7Days",
  "vaccinationSummary",
  "casesActive100k",
];

exports.MULTICARD_SCREENS = ["LAB", "HOS", "ALL"];

exports.CHART_SCREENS = [
  "MetricsComparison",
  "DailyComparison",
  "Tests",
  "Vaccination",
  "Regions100k",
  "Map",
  "Municipalities",
  "Sewage",
  "Schools",
  "SchoolStatus",
  "Patients",
  "IcuPatients",
  "CarePatients",
  "AgeGroupsTimeline",
  "WeeklyDemographics",
  "AgeGroups",
  "MetricsCorrelation",
  "Deceased",
  "ExcessDeaths",
  "Infections",
  "HcCases",
  "EuropeMap",
  "Sources",
  "Cases",
  "RegionMap",
  "Regions",
  "PhaseDiagram",
  "Spread",
  "WorldMap",
  "Ratios",
  "HCenters",
];
