name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn

      - name: yarn install
        run: |
          yarn --prod
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        if: github.ref == 'refs/heads/master'
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: TWandFB_BOT
          zip_file: bundle.zip
